In [1]:
import numpy as np

In [2]:
# create a array and know it shape
print(np.array([[1,2,3],[4,5,6]]).shape)

(2, 3)


In [3]:
# get the dimension of an numpy array
a = np.array([[1,2,3,4],[5,6,7,8]], dtype="int32")
a.ndim

2

In [4]:
# Get the type and size of the array
a.dtype
a.itemsize # .itemsize is the bytes and the .size is the size of the array
a.nbytes # Float is bigger than int

32

In [5]:
# change a value in the numpy array
b = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [6]:
# Get a specific elements [row, col], [startindex:endIndex:step]
b[:, 1]
b[0, :-1]
b[0, 2:-1:3]
b[1, 1:-1:3] = 20, 21, 22

In [7]:
# 3d arr example 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c.ndim
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
#Display a element(Work outside In) and replace elements
c[:,:,1] = [[1,2],[3,4]]
c[:,:,1] = [[2,4],[6,8]]
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
# create a diffent value matrix
np.zeros((5,5), dtype='int32')
d = np.ones([5,5])
np.full((5,5,5), 10)
np.full_like(d, 3)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [10]:
# Init a Random dec Numbers 
np.random.rand(2,3)  
np.random.random_sample(d.shape)

array([[0.01074069, 0.86442835, 0.34904348, 0.21486521, 0.90157512],
       [0.12335945, 0.84189972, 0.92243722, 0.54104684, 0.37150207],
       [0.0311442 , 0.04805067, 0.41862851, 0.88049449, 0.46407194],
       [0.32707762, 0.99035729, 0.14643566, 0.27655075, 0.71110858],
       [0.62424739, 0.40879762, 0.23224336, 0.02703264, 0.06964954]])

In [11]:
# Random Integer Numbers
np.random.randint(9, size=(10,10))
np.random.randint(-1,9, size=(9,9))

array([[ 7,  2, -1,  4,  7,  7, -1,  8,  5],
       [ 3,  2,  6,  8,  7,  0,  2,  7, -1],
       [ 2,  0,  3,  0,  8,  6,  8,  5,  2],
       [ 6,  7,  7,  3,  5,  4,  0,  8,  1],
       [ 0,  1,  4,  3,  4,  0,  6,  4,  5],
       [ 0,  2,  1,  6,  3,  2,  1,  1,  7],
       [ 5,  8,  5,  4,  6,  1,  1, -1,  6],
       [ 8,  6,  3,  8,  3,  6,  1,  1,  1],
       [ 4,  0,  1,  8, -1,  4,  3,  1,  2]])

In [12]:
# Create a Identit matrix == square
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
# repeat the array 
e = np.array([[2,4,6,8]])
r1 = np.repeat(e, 4, axis=0)
r1

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

### Coding Challenge

In [14]:
# challenge array
f = np.ones([5,5], dtype='int16')
f[1:-1, 1:-1] = [0,0,0]
f[2, 2:-2] = 9
print(f)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be Careful of Copying Array!!

In [15]:
g = np.array([1,2,3,4,5])
# inherits to every changes on g1
g1 = g 
# best options is .copy func
g1 = g.copy()
print(g)
g1[0] = 100
g1

[1 2 3 4 5]


array([100,   2,   3,   4,   5])

### Math of Numpy

In [16]:
h = np.array([1,2,3,4,5])
h + 2 # adds all to the elements 
h - 2 # minus all to the elements
h / 2 # divide all to the elements
h * 2 # multiply all to the elements
h % 2 # modulo all to the elements
h ** 2 # raise all to the elements
# Take the sin
np.sin(h)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### Linear Algebra 

In [17]:
i = np.full([2,3], 1)
print(i)
j = np.full([3,2], 2)
print(j)
np.matmul(i, j)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [18]:
#  Find determinant 
i = np.identity(9)
np.linalg.det(i)

1.0

### Statistics


In [19]:
stat = np.array([[4,2,9],[3,5,6]])
np.min(stat, axis=0)

array([3, 2, 6])

### Reorganizing Array

In [20]:
# Vertically stacking vertors
l1 = np.array([1,2,3,4,5])
l2 = np.array([6,7,8,9,10])
np.vstack([l2,l1])

# horizontal stack 
l1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
l2 = np.array([[6,7,8,9,10],[6,7,8,9,10]])
np.hstack([l1,l2]) 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
# Reshaping array
k = np.random.randint(19, size=(2,2,2,2))
k.reshape(4,4)


array([[15,  4, 13,  7],
       [ 2, 11, 15,  0],
       [ 6, 15,  4,  0],
       [10,  8, 12, 16]])

### Misc

In [41]:
m = np.genfromtxt('arr.txt', delimiter=',', dtype='int32')
m1 = m.reshape([6,5])

### Bolean Masking and Advance Indexing

In [30]:
# advance indexing, also you can index using a list
m % 2 != 1 
((m >= 17) & (m % 2 == 0))

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [109]:
m1[2:-2, 0:-3]
m1[[0,1,2,3],[1,2,3,4]]
m1[[0,4,5],-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int32)