In [158]:
# Vertically stacking vertors
l1 = np.array([1,2,3,4,5])
l2 = np.array([6,7,8,9,10])
np.vstack([l2,l1])

# horizontal stack 
l1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
l2 = np.array([[6,7,8,9,10],[6,7,8,9,10]])
np.hstack([l1,l2]) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
import numpy as np

In [24]:
# create a array and know it shape
print(np.array([[1,2,3],[4,5,6]]).shape)

(2, 3)


In [26]:
# get the dimension of an numpy array
a = np.array([[1,2,3,4],[5,6,7,8]], dtype="int32")
a.ndim

2

In [38]:
# Get the type and size of the array
a.dtype
a.itemsize # .itemsize is the bytes and the .size is the size of the array
a.nbytes # Float is bigger than int

32

In [41]:
# change a value in the numpy array
b = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [81]:
# Get a specific elements [row, col], [startindex:endIndex:step]
b[:, 1]
b[0, :-1]
b[0, 2:-1:3]
b[1, 1:-1:3] = 20, 21, 22

(2, 10)

In [94]:
# 3d arr example 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c.ndim
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [222]:
#Display a element(Work outside In) and replace elements
c[:,:,1] = [[1,2],[3,4]]
c[:,:,1] = [[2,4],[6,8]]
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [72]:
# create a diffent value matrix
np.zeros((5,5), dtype='int32')
d = np.ones([5,5])
np.full((5,5,5), 10)
np.full_like(d, 3)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [220]:
# Init a Random dec Numbers 
np.random.rand(2,3)
np.random.random_sample(d.shape)

array([[0.85118791, 0.05163308, 0.61116355, 0.89541041, 0.3753424 ],
       [0.30270353, 0.73630706, 0.68446241, 0.41525022, 0.97329876],
       [0.55101335, 0.06006789, 0.80770043, 0.79572449, 0.3568872 ],
       [0.41216352, 0.09834448, 0.76168182, 0.90478651, 0.30846093],
       [0.78767697, 0.22597653, 0.50145159, 0.80293589, 0.47837318]])

In [4]:
# Random Integer Numbers
np.random.randint(9, size=(10,10))
np.random.randint(-1,9, size=(9,9))

array([[ 0,  6,  3,  3,  1,  7,  1,  4,  5],
       [ 1, -1,  5,  7,  0,  1,  8, -1,  1],
       [ 2,  4,  4,  5,  5,  4,  8,  0,  3],
       [ 8,  2,  0,  0,  7,  3,  1,  4,  5],
       [-1, -1,  1, -1,  3,  4,  8,  2,  3],
       [ 0,  4,  4,  7,  3,  8,  1,  5,  8],
       [-1,  4,  5,  6,  7,  1,  4, -1,  2],
       [ 3,  1,  3,  3, -1, -1,  0,  0,  6],
       [ 0,  6, -1, -1,  3,  8,  8,  1, -1]])

In [10]:
# Create a Identit matrix == square
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
# repeat the array 
e = np.array([[2,4,6,8]])
r1 = np.repeat(e, 4, axis=0)
r1

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

### Coding Challenge

In [47]:
# challenge array
f = np.ones([5,5], dtype='int16')
f[1:-1, 1:-1] = [0,0,0]
f[2, 2:-2] = 9
print(f)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be Careful of Copying Array!!

In [59]:
g = np.array([1,2,3,4,5])
# inherits to every changes on g1
g1 = g 
# best options is .copy func
g1 = g.copy()
print(g)
g1[0] = 100
g1

[1 2 3 4 5]


array([100,   2,   3,   4,   5])

### Math of Numpy

In [70]:
h = np.array([1,2,3,4,5])
h + 2 # adds all to the elements 
h - 2 # minus all to the elements
h / 2 # divide all to the elements
h * 2 # multiply all to the elements
h % 2 # modulo all to the elements
h ** 2 # raise all to the elements
# Take the sin
np.sin(h)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### Linear Algebra 

In [77]:
i = np.full([2,3], 1)
print(i)
j = np.full([3,2], 2)
print(j)
np.matmul(i, j)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [84]:
#  Find determinant 
i = np.identity(9)
np.linalg.det(i)

1.0

### Statistics


In [94]:
stat = np.array([[4,2,9],[3,5,6]])
np.min(stat, axis=0)

array([3, 2, 6])

### Reorganizing Array

In [135]:
# Reshaping array
k = np.random.randint(19, size=(2,2,2,2))
k.reshape(4,4)


array([[ 4, 13,  5,  5],
       [18,  7, 18,  3],
       [ 4, 17,  4, 10],
       [12, 13,  6, 17]])